---
title: "EDA"
output: html_notebook
editor_options: 
  markdown: 
    wrap: 72
---

## Preliminares

```{r}
library(tidyverse)
library(magrittr)
library(skimr)
library(janitor)
```

### Importacion

```{r}
data <- read_csv('Data/WA_Fn-UseC_-Telco-Customer-Churn.csv')
```

#### Verificar y corregir columnas

```{r}
data %>% glimpse
```

```{r}
data %>% 
  mutate(
    SeniorCitizen= factor(SeniorCitizen, levels= c(0, 1), 
                             labels= c('no', 'si') )
  ) ->
  data
```

# EDA

## EDA Univariado

```{r}
skim( data)
```

```{r}
data %>% 
  reframe( 
    tibble(
      Descrip= c('P_0', 'P_02', 'P_25', 'P_50' , 'P_75', 'P_98', 'P_100') ,
      Valor= quantile( TotalCharges, c(0, 0.2, 0.25, 0.50 ,0.75, 0.98, 1), na.rm= T)
    )
    )
```

## EDA Multivariado

### Room 2

#### Genero vs Churn

**Tabla**

```{r}

```

**Grafico**

```{r}

```

**Interpretacion**

#### PhoneService vs Churn

```{r}

```

**Interpretacion**

### Room 4

### Room 6

### Room 8

#Eda Bivariado entre churn y Dependents


```{r}
data %>% tabyl(Churn, Dependents ) -> t1

t1 %>% adorn_totals(c("row", "col")) %>% adorn_percentages("all") %>%
adorn_pct_formatting(rounding = "half up", digits = 0) %>% adorn_ns() %>%
  adorn_title("combined") %>% knitr::kable()

data %>% count(Churn, Dependents) %>% mutate(porc = n / sum(n)) %>%
ggplot(aes(Dependents, n, fill = Churn)) + geom_bar(stat = 'identity') +
geom_text(aes(label = scales::percent(porc), y = n, vjust = 1)) +
labs(title = "Churn vs Dependents", x = "Dependents", y = "Count") +
theme_minimal()


```



#Eda Bivariado entre churn y OnlineSecurity


```{r}


data %>% tabyl(Churn,OnlineSecurity ) -> t2

t2 %>% adorn_totals(c("row", "col")) %>% adorn_percentages("all") %>%
adorn_pct_formatting(rounding = "half up", digits = 0) %>% adorn_ns()%>% adorn_title("combined")%>% knitr::kable()

data %>% count(Churn, OnlineSecurity) %>% mutate(porc = n / sum(n)) %>%
  ggplot(aes(OnlineSecurity, n, fill = Churn)) + geom_bar(stat =
'identity') + geom_text(aes(label = scales::percent(porc), y = n, vjust
= 1)) + labs(title = "Churn vs OnlineSecurity", x = "OnlineSecurity", y
= "Count")


```

#Eda Bivariado entre churn y Total Charges

```{r}

data %>%  group_by(Churn) %>% 
  summarise(n = n(),
            promedio = mean(TotalCharges,na.rm = T),
            n_missing = sum(is.na(TotalCharges)),
            desv = sd(TotalCharges, na.rm =T)) -> t4
t4

data %>%
  ggplot(aes(x = Churn, y = TotalCharges, fill = Churn)) +
  geom_boxplot() +
  stat_summary(fun = mean, geom = "point", shape = 3, size = 3, color = "white", position = position_dodge(width = 0.75)) +
  labs(title = "Churn vs Total Charges",
       x = "Churn",
       y = "Total Charges")

```




### Room 10
